
##########
## 23.2 ##
##########
dia.url <- "http://www.amstat.org/publications/jse/v9n2/4cdata.txt"
diamonds <- read.table(dia.url)
names(diamonds) <- c("Carat","Color","Clarity","Cert","Price")
#(a)
dev.new(width=6,height=6)
par(mar=c(0,4,2,0))
##(i)
boxplot(diamonds$Price~diamonds$Cert,axes=FALSE,frame=FALSE,main="Diamond Prices by Certification")
##(ii)
axis(2,at=seq(0,18000,2000),las=1,tcl=1,mgp=c(3,0.5,0))
##(iii)
text(locator(1),"SGD$",xpd=TRUE)
text(locator(1),"GIA",cex=1.5)
text(locator(1),"HRD",cex=1.5)
text(locator(1),"IGI",cex=1.5)
#(b)
dev.new(width=8,height=7)
par(mar=c(2,5,3,5),oma=c(2,rep(1,3)))
##(i)
plot(diamonds$Price~diamonds$Carat,col=c("red","green","blue")[as.numeric(diamonds$Cert)],axes=FALSE,ann=FALSE)
box(bty="u")
##(ii)
axis(1,at=seq(0.2,1.1,0.1),font=4,mgp=c(3,0.5,0))
axis(1,at=seq(0.15,1.05,0.1),tcl=-0.25,labels=FALSE)
##(iii)
axis(2,at=seq(1000,17000,2000),las=1,font=4)
axis(4,at=seq(1000,11000,1000)*1.37,labels=seq(1000,11000,1000),las=1,font=4)
##(iv)
dia.fit <- lm(Price~Carat+I(Carat^2),data=diamonds)
carat.seq <- seq(min(diamonds$Carat),max(diamonds$Carat),length=100)
dia.pred <- predict(dia.fit,newdata=data.frame(Carat=carat.seq),interval="prediction")
lines(carat.seq,dia.pred[,1],col="gray",lwd=2)
lines(carat.seq,dia.pred[,2],col="gray",lty=2)
lines(carat.seq,dia.pred[,3],col="gray",lty=2)
##(v)
expr1 <- expression("USD$"%~~%1.37%*%"SGD$")
expr2 <- expression(paste("Price"==beta[0]+beta[1],"Carat",+beta[2],"Carat"^2))
##(vi)
mtext("CARAT",side=1,line=0,outer=TRUE)
mtext("SGD$",side=2,line=4)
mtext("Scatterplot of Diamond Price by Carat and Certification",side=3,line=2,cex=1.5)
mtext(expr1,side=4,line=4)
##(vii)
interactive.arrow(label=expr2)
##(viii)
legend(locator(1),legend=levels(diamonds$Cert),col=c("red","green","blue"),pch=1)

